### ISSUE TITLE
INSPIRE challenge webinar - check and correct time

### ISSUE THREAD

**Issue by MarcoMinghini** [inspire-helsinki-2019/challenge#19]
The webinar on the challenge "Let's make the most out of INSPIRE!" is scheduled for **July 10 at 2:00 pm CET** (corresponding to 3:00 pm Italy time), which is different than 2:00 pm UTC (as it now appears on the website). So the website should be corrected.
Thank you!

**Comment by sampov2** [comment]
Thanks, this has now been corrected. The reason for the mistake was because the webex system you're using is actually giving the wrong information. The page https://ecwacs.webex.com/webappng/sites/ecwacs/meeting/info/131767612266781742?MTID=m64e9b0d28b7450b66ac81db92c02288b says "15:00 - 16:30 Wednesday, 10 Jul 2019 (UTC+01:00) Brussels, Copenhagen, Madrid, Paris" even though in July 10, Brussels is UTC +2. It would be good if you could fix this, but it could be an issue in webex itself.

**Comment by MarcoMinghini** [comment]
Thanks so muc @sampov2, really appreciated.
@alexanderkotsev let's have a look tomorrow!
